BEGIN;

-- Core tables used by the current AGP API.
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    matricule TEXT NOT NULL UNIQUE,
    role TEXT NOT NULL DEFAULT 'READER',
    function_name TEXT,
    service TEXT,
    phone TEXT,
    password_hash TEXT,
    active SMALLINT NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_leave_balances (
    user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    balance NUMERIC NOT NULL DEFAULT 0 CHECK (balance >= 0)
);

CREATE TABLE IF NOT EXISTS user_leave_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    type TEXT NOT NULL,
    request_date TEXT NOT NULL,
    date_start TEXT NOT NULL,
    date_end TEXT NOT NULL,
    holidays INTEGER NOT NULL DEFAULT 0,
    number_of_days INTEGER NOT NULL DEFAULT 0,
    address TEXT NOT NULL DEFAULT '',
    balance_before NUMERIC NOT NULL DEFAULT 0,
    balance_after NUMERIC NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'VALIDE'
);

CREATE TABLE IF NOT EXISTS user_reminders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    due_at TIMESTAMPTZ NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_user_reminders_owner_due
    ON user_reminders (user_id, is_completed, due_at, id);

CREATE TABLE IF NOT EXISTS user_sessions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash TEXT NOT NULL UNIQUE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    expires_at TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dossier_history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_id BIGINT NOT NULL,
    label TEXT NOT NULL,
    note TEXT NOT NULL,
    actor TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dossier_attachments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_id BIGINT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL,
    size TEXT NOT NULL,
    uploaded_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_url TEXT
);

CREATE TABLE IF NOT EXISTS dossier_discussions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_id BIGINT NOT NULL,
    kind TEXT NOT NULL CHECK (kind IN ('remark', 'clarification')),
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Ouverte',
    actor TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Procurement workflow: one AO can contain several lots and contracts.
CREATE TABLE IF NOT EXISTS dossiers_ao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reference VARCHAR(60) NOT NULL UNIQUE,
    intitule VARCHAR(250) NOT NULL,
    service_demandeur VARCHAR(150),
    responsable_id INTEGER REFERENCES users(id) ON DELETE SET NULL,
    mode_passation VARCHAR(100),
    nature_depense VARCHAR(60),
    nature_commande VARCHAR(60),
    commission_depot VARCHAR(150),
    commission_competente VARCHAR(10) CHECK (commission_competente IN ('CAE', 'CME', 'CRA')),
    statut VARCHAR(40) NOT NULL DEFAULT 'À lancer' CHECK (statut IN (
        'À lancer', 'Préparation AO', 'AO lancée', 'Évaluation',
        'Décision commission', 'Attribué', 'Contrat signé', 'Exécution', 'Clôturé'
    )),
    resultat_decision VARCHAR(20) NOT NULL DEFAULT 'EN_ATTENTE' CHECK (resultat_decision IN (
        'EN_ATTENTE', 'ATTRIBUE', 'INFRUCTUEUX', 'SANS_SUITE'
    )),
    date_reception_demande DATE,
    date_validation_dccc DATE,
    date_approbation_commission DATE,
    date_lancement_ao DATE,
    date_ouverture_plis DATE,
    date_decision DATE,
    nombre_lots INTEGER NOT NULL DEFAULT 1 CHECK (nombre_lots > 0),
    montant_estime NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (montant_estime >= 0),
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS dossier_lots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_ao_id BIGINT NOT NULL REFERENCES dossiers_ao(id) ON DELETE CASCADE,
    numero_lot INTEGER NOT NULL CHECK (numero_lot > 0),
    intitule VARCHAR(250) NOT NULL,
    montant_estime NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (montant_estime >= 0),
    titulaire_retenu VARCHAR(200),
    statut VARCHAR(30) NOT NULL DEFAULT 'EN_ATTENTE' CHECK (statut IN (
        'EN_ATTENTE', 'ATTRIBUE', 'INFRUCTUEUX', 'SANS_SUITE'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (dossier_ao_id, numero_lot)
);

CREATE TABLE IF NOT EXISTS contrats (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_ao_id BIGINT NOT NULL REFERENCES dossiers_ao(id) ON DELETE RESTRICT,
    lot_id BIGINT REFERENCES dossier_lots(id) ON DELETE RESTRICT,
    numero_contrat VARCHAR(80) NOT NULL UNIQUE,
    titulaire VARCHAR(200) NOT NULL,
    objet VARCHAR(250) NOT NULL,
    montant NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (montant >= 0),
    devise VARCHAR(10) NOT NULL DEFAULT 'TND',
    date_intention_commande DATE,
    date_validation_juridique DATE,
    date_signature_titulaire DATE,
    date_signature_dg DATE,
    date_enregistrement_fiscal DATE,
    date_reception_contrat DATE,
    date_echeance_caution_definitive DATE GENERATED ALWAYS AS
        (date_reception_contrat + 20) STORED,
    statut VARCHAR(40) NOT NULL DEFAULT 'EN_PREPARATION' CHECK (statut IN (
        'EN_PREPARATION', 'EN_VALIDATION_JURIDIQUE', 'EN_SIGNATURE',
        'ENREGISTRE', 'EN_EXECUTION', 'TERMINE', 'CLOTURE'
    )),
    commentaire_juridique TEXT,
    date_debut DATE,
    date_fin DATE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (lot_id IS NULL OR dossier_ao_id IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS cautionnements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_ao_id BIGINT REFERENCES dossiers_ao(id) ON DELETE CASCADE,
    contrat_id BIGINT REFERENCES contrats(id) ON DELETE CASCADE,
    type_caution VARCHAR(20) NOT NULL CHECK (type_caution IN ('PROVISOIRE', 'DEFINITIVE')),
    montant NUMERIC(18, 3) NOT NULL DEFAULT 0 CHECK (montant >= 0),
    date_reception DATE,
    date_restitution DATE,
    date_echeance DATE,
    statut VARCHAR(20) NOT NULL DEFAULT 'ATTENTE' CHECK (statut IN (
        'ATTENTE', 'RECU', 'RESTITUE', 'EXPIRE'
    )),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CHECK (dossier_ao_id IS NOT NULL OR contrat_id IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_caution_definitive_par_contrat
    ON cautionnements (contrat_id)
    WHERE type_caution = 'DEFINITIVE' AND contrat_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS notifications_rappels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_ao_id BIGINT REFERENCES dossiers_ao(id) ON DELETE CASCADE,
    contrat_id BIGINT REFERENCES contrats(id) ON DELETE CASCADE,
    type_rappel VARCHAR(50) NOT NULL,
    priorite VARCHAR(20) NOT NULL DEFAULT 'MOYENNE' CHECK (priorite IN ('FAIBLE', 'MOYENNE', 'HAUTE', 'CRITIQUE')),
    message VARCHAR(1000) NOT NULL,
    date_emission TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_echeance DATE,
    statut VARCHAR(20) NOT NULL DEFAULT 'OUVERT' CHECK (statut IN ('OUVERT', 'TRAITE', 'ANNULE')),
    CHECK (dossier_ao_id IS NOT NULL OR contrat_id IS NOT NULL)
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_rappel_caution_ouvert_par_contrat
    ON notifications_rappels (contrat_id, type_rappel)
    WHERE contrat_id IS NOT NULL AND type_rappel = 'CAUTION_DEFINITIVE' AND statut = 'OUVERT';

CREATE TABLE IF NOT EXISTS historique_modifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dossier_ao_id BIGINT REFERENCES dossiers_ao(id) ON DELETE SET NULL,
    contrat_id BIGINT REFERENCES contrats(id) ON DELETE SET NULL,
    table_source VARCHAR(60) NOT NULL,
    action_type VARCHAR(20) NOT NULL,
    champ VARCHAR(80),
    ancienne_valeur JSONB,
    nouvelle_valeur JSONB,
    modifie_par VARCHAR(150),
    modifie_le TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_dossiers_ao_statut ON dossiers_ao (statut);
CREATE INDEX IF NOT EXISTS ix_contrats_dossier ON contrats (dossier_ao_id);
CREATE INDEX IF NOT EXISTS ix_cautionnements_echeance ON cautionnements (date_echeance, statut);
CREATE INDEX IF NOT EXISTS ix_rappels_ouverts ON notifications_rappels (date_echeance) WHERE statut = 'OUVERT';

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'info' CHECK (type IN ('info', 'warning', 'success', 'alert')),
    link TEXT,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS ix_notifications_user_read_created
    ON notifications (user_id, is_read, created_at DESC, id DESC);

CREATE TABLE IF NOT EXISTS notification_delivery_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id BIGINT NOT NULL REFERENCES notifications(id) ON DELETE CASCADE,
    channel TEXT NOT NULL CHECK (channel IN ('email', 'sms')),
    payload JSONB NOT NULL,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'processing', 'sent', 'failed')),
    attempts INTEGER NOT NULL DEFAULT 0,
    available_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMPTZ,
    last_error TEXT
);

CREATE INDEX IF NOT EXISTS ix_notification_jobs_pending
    ON notification_delivery_jobs (status, available_at, id);

-- Shows contracts whose definitive guarantee has not yet been recorded.
CREATE OR REPLACE VIEW v_cautions_definitives_a_surveiller AS
SELECT
    c.id AS contrat_id,
    c.numero_contrat,
    c.dossier_ao_id,
    d.reference AS reference_dossier,
    c.titulaire,
    c.date_reception_contrat,
    c.date_echeance_caution_definitive,
    c.date_echeance_caution_definitive - CURRENT_DATE AS jours_restants,
    CASE
        WHEN c.date_echeance_caution_definitive < CURRENT_DATE THEN 'EN_RETARD'
        ELSE 'A_SURVEILLER'
    END AS alerte
FROM contrats c
JOIN dossiers_ao d ON d.id = c.dossier_ao_id
WHERE c.date_reception_contrat IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM cautionnements ca
      WHERE ca.contrat_id = c.id
        AND ca.type_caution = 'DEFINITIVE'
        AND ca.statut = 'RECU'
  );

COMMIT;